GET http://0.0.0.0:890/demo/error HTTP/1.1
token: 7678267382afe234uawe09qad93

POST http://0.0.0.0:890/demo/test HTTP/1.1
token: 7678267382afe234uawe09qad93
Content-Type: application/json

{
    "aciton":"test",
    "valid":true
}

POST http://0.0.0.0:890/demo/demo HTTP/1.1
token: f51c7185b3569f0536f165aa13459afc
Content-Type: application/json

{
    "username":"test",
    "password":"test"
}

GET http://0.0.0.0:890/index.php?r=demo/error HTTP/1.1
token: 7678267382afe234uawe09qad93


GET http://0.0.0.0:890/index.php/site/error HTTP/1.1